name: Release

on: workflow_dispatch

jobs:
  get-version:
    name: semantic-release
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic-release.outputs.new_release_published }}
      new-release-version: ${{ steps.semantic-release.outputs.new_release_version }}
      new-release-channel: ${{ steps.semantic-release.outputs.new_release_channel }}
      new_release_notes:  ${{ steps.semantic-release.outputs.new_release_channel }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'intellecta-lk/intellecta'
          token: ${{secrets.PRIVATE_TOKEN}}
      - id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          working_directory: app
          # dry_run: true
          tag_format: v${version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.semantic-release.outputs.new_release_version }}"

  build:
    runs-on: ubuntu-latest
    needs: get-version
    if: needs.get-version.outputs.new-release-published == 'true'
    steps:
      - run: echo "${{ needs.get-version.outputs.new-release-version }}"

 
    

  release:
    runs-on: ubuntu-latest
    needs: 
      - build
      - get-version
    if: needs.get-version.outputs.new-release-published == 'true'
    steps:
      - name: Build
        run: |
          touch Release.txt
          echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      # - name: Create tag
      #   run: git tag ${{ steps.semantic-release.outputs.new-release-version }}
      - name: Release
        # uses: softprops/action-gh-release@v1
        # with:
        #   tag_name: ${{ steps.semantic-release.outputs.new-release-version }}
        #   body: ${{ needs.get-version.outputs.new-release-notes }}
        #   files: |
        #     Release.txt
        # env:
        #   GITHUB_TOKEN: ${{secrets.PRIVATE_TOKEN}}
        run: echo "${{ needs.get-version.outputs.new-release-version }}"
      - run: | 
          gh release create ${{ needs.get-version.outputs.new-release_version }}  \ 
           Release.txt \
          -R https://github.com/${{github.repository}} \
        env:
          GH_TOKEN: ${{ github.token }}


  delete_tag_if_failed:
    runs-on: ubuntu-latest
    needs: 
       - build
       - get-version
       - release
    if: always() && contains(needs.*.result, 'failure')
    steps:
      - run: gh release delete ${{ needs.get-version.outputs.new-release-version }} --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
          

      
    
    
    
      
    
