name: Flutter App Build

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  BASE_REPO: intellecta-lk/flutter-idx

jobs:
  # android-build:
  #   runs-on: ubuntu-latest
  #   # permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         repository: ${{ env.BASE_REPO }}
  #         token: ${{secrets.PRIVATE_TOKEN}}
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable 
  #     - run: flutter pub get
  #     - run: flutter pub upgrade win32
  #     # - run: flutter test
  #     # - run: flutter build apk
  #     - run: flutter build appbundle
  #     - uses: actions/cache/save@v4
  #       with:
  #         path: |
  #           build/app/outputs/bundle/release/*.aab
  #         key: intellecta-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
  #         enableCrossOsArchive: true

  
  windows-build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.BASE_REPO }}
          token: ${{secrets.PRIVATE_TOKEN}}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 
      - run: flutter pub get
      - run: flutter pub upgrade win32
      - run: flutter build windows
      - uses: actions/upload-artifact@master
        with:
          name: windows
          path: build\windows\runner\Release
      - run: dart run msix:create
      - uses: actions/cache/save@v4
        with:
          path: |
            build/windows/runner/Release/*.exe
          key: intellecta-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
          enableCrossOsArchive: true

  # release:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - android-build
  #     - windows-build
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses:  actions/cache/restore@v4
  #       with:
  #         path: | 
  #            build/app/outputs/bundle/release/*.aab
  #         key: intellecta-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
  #         enableCrossOsArchive: true
  #     - uses:  actions/cache/restore@v4
  #       with:
  #           path: | 
  #              build/windows/x64/runner/Release/*.exe
  #           key: intellecta-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
  #           enableCrossOsArchive: true
  #     - run: ls -la
  #     - run: |
  #         gh release create ${{ inputs.version }}  \
  #         -R https://github.com/${{github.repository}}  \
  #         -- build/windows/x64/runner/Release/*.exe  \
  #            build/app/outputs/bundle/release/*.aab
  #       env:
  #         GH_TOKEN: ${{ github.token }}