name: Flutter App Build

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  BASE_REPO: intellecta-lk/flutter-idx

jobs:
  android-build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.BASE_REPO }}
          token: ${{secrets.PRIVATE_TOKEN}}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 
      - run: flutter pub get
      - run: flutter pub upgrade win32
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - run: |
          gh release create ${{ inputs.version }}  \
          -R https://github.com/${{github.repository}}  \
          -- build/app/outputs/bundle/release/*
        env:
          GH_TOKEN: ${{ github.token }}
